### ISSUE TITLE
clean() got an unexpected keyword argument 'fix_unicode'

### ISSUE THREAD

**Issue by guyewhite** [pszemraj/vid2cleantxt#19]
So excited to get this working! I get the following error when attempting to run the example CLI from the readme (fresh M2-Ultra Mac Studio out of box):

```
python examples/TEST_folder_edition/dl_src_videos.py
python vid2cleantxt/transcribe.py -i ./examples/TEST_folder_edition/ -m openai/whisper-small

```

Results in the following error: 

```
% python vid2cleantxt/transcribe.py -i ./examples/TEST_folder_edition/ -m openai/whisper-small
data folder is set to `/Users/guyewhite/anaconda3/lib/python3.11/site-packages/neuspell/../data` script

Loading models @ Jul-29-2023_-16-21-24 - may take some time...
if RT seems excessive, try --verbose flag or checking logfile

Found 10 audio or video files in /Users/guyewhite/Desktop/vid2cleantxt-master/examples/TEST_folder_edition
transcribing...:   0%|                                                   | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):                                       | 0/41 [00:00<?, ?it/s]
  File "/Users/guyewhite/Desktop/vid2cleantxt-master/vid2cleantxt/transcribe.py", line 807, in <module>
    output_text, output_metadata = transcribe_dir(
                                   ^^^^^^^^^^^^^^^
  File "/Users/guyewhite/Desktop/vid2cleantxt-master/vid2cleantxt/transcribe.py", line 663, in transcribe_dir
    transcribe_video_whisper(
  File "/Users/guyewhite/Desktop/vid2cleantxt-master/vid2cleantxt/transcribe.py", line 263, in transcribe_video_whisper
    chunk_directory = prep_transc_pydub(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/guyewhite/Desktop/vid2cleantxt-master/vid2cleantxt/audio2text_functions.py", line 123, in prep_transc_pydub
    preamble = trim_fname(_vid2beconv)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyewhite/Desktop/vid2cleantxt-master/vid2cleantxt/v2ct_utils.py", line 273, in trim_fname
    clean_name = cleantxt_wrap(current_name)  # helper fn to clean up text
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/guyewhite/Desktop/vid2cleantxt-master/vid2cleantxt/v2ct_utils.py", line 229, in cleantxt_wrap
    cleaned_text = clean(
                   ^^^^^^
TypeError: clean() got an unexpected keyword argument 'fix_unicode'
Creating .wav audio clips:   0%|                                         | 0/41 [00:00<?, ?it/s]
```

**Comment by guyewhite** [comment]
Issue solved by re-running `pip install -r requirements.txt`. Noticed that `pyqt5` was not installed. To correct, did the following commands:

```
pip3 install pyqt5 —-config-settings —-confirm-license= —-verbose
```

Closing issue.
