### ISSUE TITLE
neuspell initialization not working

### ISSUE THREAD

**Issue by pszemraj** [pszemraj/vid2cleantxt#7]
- neuspell unpickling of default models no longer works
- need to add backup spell-checking function

```
data folder is set to `/usr/local/lib/python3.7/dist-packages/neuspell/../data` script
Downloading: 100% 208k/208k [00:00<00:00, 632kB/s]
Downloading: 100% 29.0/29.0 [00:00<00:00, 25.8kB/s]
Downloading: 100% 426k/426k [00:00<00:00, 1.03MB/s]
Downloading: 100% 570/570 [00:00<00:00, 504kB/s]

Loading models @ Feb-23-2022_-12-35-31 - may take some time...
if RT seems excessive, try --verbose flag or checking logfile
Downloading: 100% 212/212 [00:00<00:00, 181kB/s]
Downloading: 100% 138/138 [00:00<00:00, 121kB/s]
Downloading: 100% 1.34k/1.34k [00:00<00:00, 1.20MB/s]
Downloading: 100% 291/291 [00:00<00:00, 252kB/s]
Downloading: 100% 85.0/85.0 [00:00<00:00, 70.1kB/s]
Loading hubert model - facebook/hubert-large-ls960-ft
Downloading: 100% 1.18G/1.18G [00:20<00:00, 60.3MB/s]
Downloading: 100% 416M/416M [00:06<00:00, 62.5MB/s]
Traceback (most recent call last):
  File "vid2cleantxt/transcribe.py", line 482, in <module>
    checker = init_neuspell()
  File "/content/vid2cleantxt/vid2cleantxt/audio2text_functions.py", line 396, in init_neuspell
    checker.from_pretrained()
  File "/usr/local/lib/python3.7/dist-packages/neuspell/corrector_sclstmbert.py", line 45, in from_pretrained
    self.model = load_pretrained(self.model, self.weights_path, device=self.device)
  File "/usr/local/lib/python3.7/dist-packages/neuspell/seq_modeling/sclstmbert.py", line 23, in load_pretrained
    checkpoint_data = torch.load(os.path.join(checkpoint_path, "model.pth.tar"), map_location=map_location)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by pszemraj** [comment]
see replication on master [here](https://colab.research.google.com/gist/pszemraj/adeb2ebee0cc6e4753d10a1ee18e5c07/vid2cleantxt-gpu-test-master.ipynb)

**Comment by pszemraj** [comment]
[test with GPU](https://colab.research.google.com/gist/pszemraj/c3df1b279f8fb132922d3405909d8c3a/vid2cleantxt-gpu-test-fix-neuspell.ipynb) works
